version: "3"
services:

  app:
    image: ortussolutions/commandbox:adobe2018-snapshot
    volumes:
      - ./app/:/app/
    ports:
      - "80:8080"
    environment:
      - cfconfig_adminPassword=${ADMIN_PASSWORD:-commandbox}
